--Created using senpaizuri's Puzzle Maker (updated by Naim & Larry126)
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,4)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)
--[[message
	Problems with cards with continuous effects to decrease the ammount of tributes
	In this puzzle you can perform 20 Normal Summons, to make easier to test
]]

local e0=Effect.GlobalEffect()
	e0:SetType(EFFECT_TYPE_FIELD)
	e0:SetCode(EFFECT_SET_SUMMON_COUNT_LIMIT)
	e0:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e0:SetTargetRange(1,0)
	e0:SetValue(20)
Duel.RegisterEffect(e0,tp)


local reloader=Debug.AddCard(31034919,0,0, LOCATION_REMOVED,0,POS_FACEUP)
local e1=Effect.CreateEffect(reloader)
e1:SetType(EFFECT_TYPE_IGNITION)
e1:SetRange(LOCATION_REMOVED)
e1:SetDescription(64)
e1:SetOperation(
	function (e, tp)
			Duel.SendtoDeck(Duel.GetMatchingGroup(nil,tp,LOCATION_REMOVED+LOCATION_HAND+LOCATION_ONFIELD+LOCATION_GRAVE,0,e:GetHandler()),nil,-2,REASON_RULE)
			ox1=Duel.CreateToken(tp,18993198)
			ox2=Duel.CreateToken(tp,18993198)
			diox1=Duel.CreateToken(tp,44088292)
			diox2=Duel.CreateToken(tp,44088292)
			catalyst=Duel.CreateToken(tp,65959844)
			local case1=Group.FromCards(ox1,diox1,ox2)
			Duel.SendtoHand(case1,tp,REASON_RULE)
			Duel.MoveToField(ox2,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x2)
			Duel.MoveToField(diox2,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x4)
			Duel.MoveToField(catalyst,tp,tp,LOCATION_SZONE,POS_FACEUP,true)
			Debug.Message("The number of Normal Summons you have is:  "..tonumber(20-Duel.GetActivityCount(tp,ACTIVITY_NORMALSUMMON)))
	end
)
reloader:RegisterEffect(e1)
local e2=Effect.CreateEffect(reloader)
e2:SetType(EFFECT_TYPE_IGNITION)
e2:SetRange(LOCATION_REMOVED)
e2:SetDescription(1021)
e2:SetOperation(
	function (e, tp)
			Duel.SendtoDeck(Duel.GetMatchingGroup(nil,tp,LOCATION_REMOVED+LOCATION_HAND+LOCATION_ONFIELD+LOCATION_GRAVE,0,e:GetHandler()),nil,-2,REASON_RULE)
			emp1=Duel.CreateToken(tp,86585274)
			emp2=Duel.CreateToken(tp,86585274)
			apple=Duel.CreateToken(tp,56132807)
			crowler=Duel.CreateToken(tp,50756327)
			Duel.SendtoHand(emp1,tp,REASON_RULE)
			Duel.SendtoHand(apple,tp,REASON_RULE)
			Duel.MoveToField(emp2,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x2)
			Duel.MoveToField(crowler,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x40)
			Debug.Message("The number of Normal Summons you have is:  "..tonumber(20-Duel.GetActivityCount(tp,ACTIVITY_NORMALSUMMON)))
	end
)
reloader:RegisterEffect(e2)
local e3=Effect.CreateEffect(reloader)
e3:SetType(EFFECT_TYPE_IGNITION)
e3:SetRange(LOCATION_REMOVED)
e3:SetDescription(1102)
e3:SetOperation(
	function (e, tp)
			Duel.SendtoDeck(Duel.GetMatchingGroup(nil,tp,LOCATION_REMOVED+LOCATION_HAND+LOCATION_ONFIELD+LOCATION_GRAVE,0,e:GetHandler()),nil,-2,REASON_RULE)
			rag1=Duel.CreateToken(tp,19476824)
			rag2=Duel.CreateToken(tp,19476824)
			daed1=Duel.CreateToken(tp,45960523)
			daed2=Duel.CreateToken(tp,45960523)
			factor=Duel.CreateToken(tp,20720928)
			Duel.SendtoHand(Group.FromCards(rag1,daed1),tp,REASON_RULE)
			Duel.MoveToField(rag2,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x2)
			Duel.MoveToField(daed2,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x4)
			Duel.MoveToField(factor,tp,tp,LOCATION_SZONE,POS_FACEUP,true)
			Debug.Message("The number of Normal Summons you have is:  "..tonumber(20-Duel.GetActivityCount(tp,ACTIVITY_NORMALSUMMON)))
	end
)
reloader:RegisterEffect(e3)

local e4=Effect.CreateEffect(reloader)
e4:SetType(EFFECT_TYPE_IGNITION)
e4:SetRange(LOCATION_REMOVED)
e4:SetDescription(1022)
e4:SetOperation(
	function (e, tp)
			Duel.SendtoDeck(Duel.GetMatchingGroup(nil,tp,LOCATION_REMOVED+LOCATION_HAND+LOCATION_ONFIELD+LOCATION_GRAVE,0,e:GetHandler()),nil,-2,REASON_RULE)
			condemend=Duel.CreateToken(tp,35306215)
			ixchel1=Duel.CreateToken(tp,52840267)
			ixchel2=Duel.CreateToken(tp,52840267)
			ref=Duel.CreateToken(tp,67316075)
			ixchel3=Duel.CreateToken(tp,52840267)
			ixchel4=Duel.CreateToken(tp,52840267)
			ixchel5=Duel.CreateToken(tp,52840267)
			Duel.SendtoHand(Group.FromCards(ixchel2,ref),tp,REASON_RULE)
			Duel.MoveToField(ixchel1,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x2)
			Duel.MoveToField(ixchel5,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x1)
			Duel.MoveToField(condemend,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x40)
			Duel.SendtoGrave(Group.FromCards(ixchel3,ixchel4),tp,REASON_RULE)
			--Duel.MoveToField(factor,tp,tp,LOCATION_SZONE,POS_FACEUP,true)
			Debug.Message("The number of Normal Summons you have is:  "..tonumber(20-Duel.GetActivityCount(tp,ACTIVITY_NORMALSUMMON)))
	end
)
reloader:RegisterEffect(e4)

local e4=Effect.CreateEffect(reloader)
e4:SetType(EFFECT_TYPE_IGNITION)
e4:SetRange(LOCATION_REMOVED)
e4:SetDescription(1030)
e4:SetOperation(
	function (e, tp)
			Duel.SendtoDeck(Duel.GetMatchingGroup(nil,tp,LOCATION_REMOVED+LOCATION_HAND+LOCATION_ONFIELD+LOCATION_GRAVE,0,e:GetHandler()),nil,-2,REASON_RULE)
			amar=Duel.CreateToken(tp,18988391)
			shade=Duel.CreateToken(tp,89252153)
			fus=Duel.CreateToken(tp,51632798)
			ixchel=Duel.CreateToken(tp,52840267)
			ixche2=Duel.CreateToken(tp,52840267)
			ixche3=Duel.CreateToken(tp,52840267)
			Duel.SendtoHand(Group.FromCards(shade,ixche3,fus),tp,REASON_RULE)
			Duel.MoveToField(ixchel,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x2)
			Duel.MoveToField(ixche2,tp,tp,LOCATION_MZONE,POS_FACEUP_ATTACK,true,0x1)
			Duel.SendtoGrave(amar,tp,REASON_RULE)
			Debug.Message("The number of Normal Summons you have is:  "..tonumber(20-Duel.GetActivityCount(tp,ACTIVITY_NORMALSUMMON)))
	end
)
reloader:RegisterEffect(e4)

Debug.ReloadFieldEnd()
